name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    name: Build & Test (Python ${{ matrix.python-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      # ---- Lint Stage ----
      - name: Run lint
        run: flake8 my_app tests

      # ---- Test Stage ----
      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

      # ---- Build Stage ----
      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-dist-${{ matrix.os }}-py${{ matrix.python-version }}
          path: dist/*
